#!/usr/bin/env python
#################################################### 
##  ___   ____       ____   ___  ## cs.huji.ac.il ##
## |   | /   /       \   \ |   | ##    /\         ##
## |   |/   /         \   \|   | ##   / /         ##
## |       /       __  \       | ##   \_/         ##
## |      /   ___ |  |_ \      | ##    _          ##
## |      \  / _ \|   _|/      | ##   | |  __  _  ##
## |       \/ / \ \  | /       | ##   | | /  \//  ##
## |   |\   \ \_/ /  |/   /|   | ##   | |/ /\ \   ##
## |___| \___\___/\__/___/ |___| ##   \_  /  \_\  ##
##      KeeperoftheKeys.nl       ##    /_/        ## 
####################################################

################################################################################
# Written by E.S. Rosenberg 5774/2013
#
# Description:
# This script will try to send an SMS using one or more sms-sending hosts.
# In the event of a failure it will send a message to the CSE queue.
#
# Arguments:
# 1 cellnumber
# 2 message enclosed in quotes
#
# Example call:
# /path/to/script 0501111111 "very important message"
#
# Return values:
# 0 - success!
# 2 - failure to send SMS.
#
# Dependencies:
# huji_cs_nagios_config -- contains:
# SMSPORT     - int
# smsservers  - list of hostname strings
# mail        - dict of mail related strings, keys: from, to, server
# errorString - empty list to be filled by script 
#
# @author: E.S. Rosenberg (Keeper of the Keys) <esr at mail dot hebrew dot edu>
# @license: GPLv2
################################################################################

try:
    import socket
    import sys
    import argparse
    import re
    import huji_cs_nagios_config
except Exception as e:
    print 'Failed imports: ' + str(e)
    exit(2)

def sendSMS(message, cell, host, port):
    # The listener expects the following format: [cell#][:space:][message]
    # ie.: 0501111111 my message
    #
    # Message can contain \n for newlines.
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        s.connect((host, port))
        s.sendall(cell + ' ' + message)
        answer = s.recv(32)
        s.close()

        # Currently the listener returns the number it sent the SMS followed 
        # by a message serial number in case of success, ie. 0501111111: 123
        if answer.startswith(cell) and re.search('(\d+)$', answer):
            return True

    except Exception as e:
        err = 'Trying host: {} resulted in the following error:\n{}'.format(host,
                                                                            e)
        huji_cs_nagios_config.errorString.append(err)
        return False

if __name__ == "__main__":
    parser = argparse.ArgumentParser(__file__)
    parser.add_argument('cell', help='Cellnumber', nargs = 1)
    parser.add_argument('message', help='"Message in quotes"', nargs = 1)
    parser.add_argument('zabbix_message_body',
                        help='The body of the message zabbix is trying to send,'+
                             ' *this will be ignored*', nargs = '?')

    args = parser.parse_args()

    for server in huji_cs_nagios_config.smsservers:
        if sendSMS(args.message[0], args.cell[0], 
                   server, huji_cs_nagios_config.SMSPORT):
            exit(0) # If the message was sent succesfully we're done.

    # If this code is reached the world is coming to an end....
    try:
        errorList=''
        for error in huji_cs_nagios_config.errorString:
            errorList += '\n' + str(error)
        
        import smtplib
        from email.mime.text import MIMEText
        text = str('Failed to send SMS with all sms servers, sending ' +
                   'e-mail instead on the off chance someone survived '+
                   'the zombie apocalypse and will read my important ' +
                   'message:\n\n'                                      +
                   'Desired recipient: {} \n'                          +
                   'Message content: {} \n\n'                          +
                   'Error list: '                                      +
                   '{}').format(args.cell[0], args.message[0], errorList)
        
        email = MIMEText(text)

        email['Subject'] = 'Disaster has struck! Can\'t send SMS!'
        email['From'] = huji_cs_nagios_config.mail['from']
        email['To'] = huji_cs_nagios_config.mail['to']
        s = smtplib.SMTP(huji_cs_nagios_config.mail['server'])
        s.sendmail(email['From'], email['To'], email.as_string())
        s.quit()
    except Exception as e:
        # The disaster is clearly total, give up and start digging your grave.
        print "Failed to mail" + str(e)
        exit(2)
    
    # Exit with nagios critical state code, I am not sure if nagios will check 
    # this, but if it does it should know there was a problem sending SMS.
    print "Failed to SMS, error report mailed"
    exit(2)
